import { ProductCardProps } from "@/interface/index";

export const PRODUCTS: ProductCardProps[] = [
    {
        _id: "1",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["popular"],
        brand: "FloralEssence",
        category: "oil Perfume women Perfume",
        quantity: 5,
    },
    {
        _id: "2",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume0.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["New"],
        brand: "paris",
        category: "Ouds",
        quantity: 30,
    },
    {
        _id: "3",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume1.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["Limited Edition"],
        brand: "RoseLuxury",
        category: "Designer Perfume",
        quantity: 0,
    },
    {
        _id: "4",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume0.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["Best Sells"],
        brand: "FloralEssence",
        category: "Luxury Perfume",
        quantity: 2,
    },
    {
        _id: "5",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume1.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["Trending"],
        brand: "FloralEssence",
        category: "Ouds",
        quantity: 3,
    },
    {
        _id: "6",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume2.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["popular"],
        brand: "RoseLuxury",
        category: "Luxury perfume designer perfume men Perfume women perfume unisex perfume",
        quantity: 50,
    },
    {
        _id: "7",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume3.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["New Arrival"],
        brand: "Paris",
        category: "men Perfume",
        quantity: 0,
    },
    {
        _id: "8",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume4.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["Luxury"],
        brand: "FloralEssence",
        category: "oil Perfume",
        quantity: 15,
    },
    {
        _id: "9",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume5.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["popular"],
        brand: "FloralEssence",
        category: "spray french",
        quantity: 25,
    },
    {
        _id: "10",
        name: "Designer Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume6.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["popular"],
        brand: "FloralEssence",
        category: "spray Arabic",
        quantity: 40,
    },
    {
        _id: "11",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume5.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["popular"],
        brand: "FloralEssence",
        category: "spray french",
        quantity: 25,
    },
    {
        _id: "12",
        name: "Designer Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume6.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["popular"],
        brand: "FloralEssence",
        category: "spray Arabic",
        quantity: 40,
    },
    {
        _id: "13",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume5.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["popular"],
        brand: "FloralEssence",
        category: "spray french",
        quantity: 25,
    },
    {
        _id: "14",
        name: "Designer Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume6.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["popular"],
        brand: "FloralEssence",
        category: "spray Arabic",
        quantity: 40,
    },
    {
        _id: "15",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume3.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["New Arrival"],
        brand: "Paris",
        category: "men Perfume",
        quantity: 0,
    },
    {
        _id: "16",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume2.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["popular"],
        brand: "RoseLuxury",
        category: "Luxury men Perfume women perfume unisex perfume",
        quantity: 50,
    },
    {
        _id: "17",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume0.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["New"],
        brand: "paris",
        category: "Ouds",
        quantity: 30,
    },
    {
        _id: "18",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume3.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["New Arrival"],
        brand: "Paris",
        category: "men Perfume women perfume unisex perfume",
        quantity: 0,
    },
    {
        _id: "19",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume0.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["New"],
        brand: "paris",
        category: "Ouds women perfume",
        quantity: 30,
    },
    {
        _id: "20",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume2.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["popular"],
        brand: "RoseLuxury",
        category: "Luxury men Perfume",
        quantity: 50,
    },
       {
        _id: "21",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["popular"],
        brand: "FloralEssence",
        category: "oil Perfume women perfume",
        quantity: 5,
    },
        {
        _id: "22",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume4.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["Luxury"],
        brand: "FloralEssence",
        category: "oil Perfume",
        quantity: 15,
    },
     {
        _id: "23",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume1.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["Limited Edition"],
        brand: "RoseLuxury",
        category: "Designer Perfume unisex perfume",
        quantity: 0,
    },
    {
        _id: "6",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume2.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: ["popular"],
        brand: "RoseLuxury",
        category: "Luxury perfume designer perfume men Perfume",
        quantity: 50,
    },
]
